### ISSUE TITLE
Hardcoded String values

### ISSUE THREAD

**Issue by vudin** [Turkcell/GYAppAnd#12]
Kod icerisinde kullanilan String'leri dogrudan kullanildigi yerde tanimlamak copy/paste veya farkli hatalara yol acar. Bundan kacinmak icin, UI ile ilgili String'leri `strings.xml` dosyalarinda, kodun icerisinde kullanilan Stringleri ise `public static final String BLA_BLA = "Bla bla..."` seklinde tanimlamak daha dogru olacaktir. Boylelikle encoding problemlerinden de kurtulmus olursunuz ve `build.gradle` dosyasindaki `compileOptions.encoding = "windows-1254"` satirina ihtiyac kalmaz.
### 1. Ornek:

Bu kod parcasindaki `android:text` degeri hardcoded olarak girilmis:

```
<TextView
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:id="@+id/yorumyok"
        android:textSize="25dp"
        android:textColor="@color/yorum_yazi_renk"
        android:text="Henüz Yorum Yapılmamış"
        android:visibility="invisible"
        android:layout_gravity="center"/>
```

Bunun yerine `android:text="@string/no_comments"` seklinde yazip `strings.xml` dosyasinda da `<string name="no_comments">Henüz Yorum Yapılmamış</string>` seklinde tanimlamaniz gerekir.
### 2. Ornek:

Benzer sekilde su kisimda da hardcoded bir String degeri var:

```
alertDialogBuilder.setMessage("Lütfen Internet Bağlantınızı Kontrol Ediniz.");
```

Bu gibi durumlarda da ayni sekilde `strings.xml` dosyasinda tanimlayarak kullanmak hem kodun duzeni ve okunabilirligi acisindan hem de tekrar kullanilabilmesi acisindan daha uygun olacaktir. Cozum yine ayni:

`alertDialogBuilder.setMessage(R.string.please_check_your_connection);`

`<string name="no_comments">Lütfen Internet Bağlantınızı Kontrol Ediniz.</string>`
### 3. Ornek:

Burada `Intent`e eklenen extra'lar kodun bir baska yerinde mutlaka okunacaktir. Key ve value degerlerini bu sekilde hardcoded olarak eklemek, bunlarin okunacagi yerde yazim hatasi vs. gibi sebeplerle buyuk hatalara yol acabilir.

```
i = new Intent(getActivity(), EgitimBaslikActivity.class);
i.putExtra("title", "Android 101");
i.putExtra("color", "android");
i.putExtra("nodeID", getResources().getString(R.string.android101));
startActivity(i);
```

Bundan kacinmak icin, bu gibi hardcoded degerleri `static final` olarak tanimlamak faydali olacaktir.

```
public static final String INTENT_EXTRA_TITLE = "title";
public static final String TITLE_ANDROID_101 = "Android 101";

...

i.putExtra(INTENT_EXTRA_TITLE, TITLE_ANDROID_101);

...

// Kodun baska bir yerinde bunu kullanirken:
String title = getIntent().getStringExtra(MobilFragment.INTENT_EXTRA_TITLE);
```

Bunlar sadece birkac ornek, benzer hatalar kodun hemen hemen her yerinde fark ediliyor. Bu hatalari duzeltmek hem kodun daha duzenli olmasini ve daha iyi okunabilmesini saglar hem de kod standartlarina uyulmus olur.

Kolay gelsin.

**Comment by AbdullahSa** [comment]
Merhaba,
Bahsettiğiniz önerileri tüm sınıflar ve layoutlarda uyguladık.Birçok hardcode yazı strings.xml e eklendi.Ayrıca bazı Hardcode İntent key değerleri static final değişken olarak alakalı model sınıflarında oluşturuldu ve oradan çağırıldı.Mümkün olduğunca bahsettikleriniz düzeltildi.

İlgili commitler:
https://github.com/Turkcell/GYAppAnd/commit/834a884674f2465dc2c9972050f3a17bcf1f45d3
https://github.com/Turkcell/GYAppAnd/commit/43ab2b77d0e90575cb22a949f9d07c1a767612ee
https://github.com/Turkcell/GYAppAnd/commit/95ec1344069aa1d7ded1bff38f7f3ba8eb8245a5

Tavsiyeniz için teşekkürler.
