### ISSUE TITLE
style check and ethical issues

### ISSUE THREAD

**Issue by salimkayabasi** [Turkcell/GYAppAnd#3]
This projects needs to be rewritten. As a developer I am getting too much difficulties while reading those codes.

Please do not use any Turkish word on variables or package names. 

BTW you should not forget to give credit author of codes that you **stole**. 
ie: https://github.com/ceaseless-prayer/CeaselessAndroid/blob/master/app/src/main/java/org/theotech/ceaselessandroid/transformer/ZoomOutPageTransformer.java

**Comment by mehmetaca** [comment]
Bu proje özellikle Türkiye'deki geliştiriciler için yazıldığından dolayı değişken, sınıf ve paket isimlerinin Türkçe karekter kullanmadan Türkçe kelimelerden oluşmasına karar verdik. Projenin farklı yerlerinde farklı kullanımlar varsa incelenip düzeltilecektir.

ZoomluGecis.java isimli dosya geliştirme aşamasında deneme amaçlı eklenmiş olup, projenin hiç bir yerinde aktif olarak çağrılmamıştır. Dolayısı ile bu dosyayı kaldırıyoruz.

**Comment by salimkayabasi** [comment]
Sanirim sonrada verilen bu karar degistirilip, artik yari ingilizce yari turkce daha da karisik bir hale getirilmesine karar verilmis

https://github.com/Turkcell/GYAppAnd/commit/c87f2a499210f1ce545176b344d623e5f5c5fad2

`Service` yerine `Servis` yazmaniz gerekiyor sanirim
`Utils` yerine artik `SikKullanilanlar`, `GenelAraclar`, `FaydaliAraclar` gibi bir cozum bulursunuz.

Aklima gelenler bunlar simdilik ama ya tamamen turkce isimlendirme ya da tamamen ingilizce isimlendirme yapilabilirse daha dogru olacaktir bir proje icerisideki tutarlilik icin.

Bu task'in tekrar acilmasi gerektigii dusunuyorum

**Comment by AbdullahSa** [comment]
Bu arada ilk mesajda çalıntı diye verilen kodun ( https://github.com/ceaseless-prayer/CeaselessAndroid/blob/master/app/src/main/java/org/theotech/ceaselessandroid/transformer/ZoomOutPageTransformer.java ) orjinali **http://developer.android.com/intl/es/training/animation/screen-slide.html#zoom-out**  bu linktedir. **developer.android.com sitesinden yararlanmıştım.** Ayrıca bu içerik Apache 2.0 ile lisanslanmıştır.

Düzenlenmesini düşündüğünüz yerleri pull request yaparak bize bildirebilirsiniz.
