### ISSUE TITLE
Default isimlendirmeler

### ISSUE THREAD

**Issue by BahadirBulduk** [Turkcell/GYAppAnd#5]
Default isimlendirmelerin düzeltilmesi. Örneğin ; textView1

**Comment by AbdullahSa** [comment]
Bahsi geçen default isimlendirmeler düzeltildi.
İlgili İssue:
https://github.com/Turkcell/GYAppAnd/commit/42edae4c1bb58ed2b9cabcd04fd3b57d61d025d7

Teşekkürler.
