### ISSUE TITLE
Mail işlemlerinin düzeltilmesi

### ISSUE THREAD

**Issue by ouzman** [Turkcell/GYAppAnd#7]
mail.jar'ın kaldırılıp, telefonun default mail istemcisi kullanılarak mail gönderilmesi.
Eğer mail.jar kullanılmaya devam edilecekse, gönderenin kullanıcı, alıcının gelecegiyazanlar@gmail.com olarak düzeltimesi, bununla beraber kullanıcının smtp bilgilerinin uygulamaya girdirilmesi gerek.

**Comment by mehmetaca** [comment]
İletişim sayfası tekrar düzenlenme amacıyla uygulamadan kaldırıldı.
