### ISSUE TITLE
Package yapısının yeniden düzenlenmesi

### ISSUE THREAD

**Issue by muratcanbur** [Turkcell/GYAppAnd#8]
package yapısı tam olarak oturtulamamış ve aynı zamanda isimlendirmelerde herhangi bir standart yok.

Kaynak olması açısından paylaşıyorum.

[https://medium.com/turkce/i̇yi-bir-android-uygulaması-nasıl-geliştirilir-package-yapısının-kurulması-982f0785934](url)

**Comment by AbdullahSa** [comment]
Gerekli düzenlemeler ile bu sorun giderildi.

İlgili commit:
https://github.com/Turkcell/GYAppAnd/commit/1e7b80ad3c90cf066ba9e596069c381f0e1bb2f5
