### ISSUE TITLE
Hassas bilgilerin koddan kaldırılması

### ISSUE THREAD

**Issue by ouzman** [Turkcell/GYAppAnd#9]
https://github.com/Turkcell/GYAppAnd/blob/67a3bcf85b8e1a342313a6628490f10aa40ca049/src/main/res/values/curio.xml

**Comment by BahadirBulduk** [comment]
Geleceği yazanlar elçilerinin fotoğrafları da uygulama içerisinden kaldırılabilir.

**Comment by mehmetaca** [comment]
İlgili xml dosyası düzenlendi. 
Elçilerin fotoğraflarını performans açısından uygulama içinde bulunduruyoruz.
Teşekkürler.
